Repository NeotomaDB/MetaExtractor, pull requests merged in 2023-06, with the labels that each got.

#24 Repeatable Labelled Data Splitting Process & Data Folder Structure Update
  .gitignore
  README.md
  data/article-relevance/interim/.gitkeep
  data/article-relevance/processed/.gitkeep
  data/article-relevance/raw/.gitkeep
  data/data-review-tool/interim/.gitkeep
  data/data-review-tool/processed/.gitkeep
  data/data-review-tool/raw/.gitkeep
  data/entity-extraction/interim/.gitkeep
  data/entity-extraction/processed/.gitkeep
  data/entity-extraction/raw/.gitkeep
  data/entity-extraction/raw/taxa.csv
  requirements.txt
  src/entity_extraction/baseline_entity_extraction.py
  src/preprocessing/labelling_data_split.py
  tests/entity_extraction/test_baseline_entity_extraction.py
  tests/entity_extraction/test_labelling_data_split.py
  tests/entity_extraction/test_labelling_data_split/test-label-1.txt
  tests/entity_extraction/test_labelling_data_split/test-label-2.txt
  tests/entity_extraction/test_labelling_data_split/test-label-3.txt
Labels: NER

#31 Cross Project Shared Logging Functionality
  src/logs.py
Labels: enhancement

#32 Proposed Update to sample_pipeline_output.json
  sample_pipeline_output.json
Labels: enhancement

#36 Improved NER Model Evaluation Metrics & Refactoring
  src/entity_extraction/entity_extraction_evaluation.py
  src/entity_extraction/ner_eval.py
  src/entity_extraction/training/hf_token_classification/hf_evaluate.py
  src/entity_extraction/training/spacy_ner/spacy_evaluate.py
  tests/entity_extraction/test_entity_extraction_evaluation.py
Labels: NER

#38 Updated ReadMe for Sharing with External Stakeholders
  README.md
  assets/data-review-tool.png
  assets/ffossils-logo-text.png
  assets/hugging-face-metaextractor.png
  assets/project-flow-diagram.png
Labels: docs

#42 Initial Dockerized Entity Extraction Pipeline
  .dockerignore
  docker-compose.yml
  docker/entity-extraction-pipeline/Dockerfile
  docker/entity-extraction-pipeline/README.md
  docker/entity-extraction-pipeline/requirements.txt
  requirements.txt
  src/entity_extraction/baseline_entity_extraction.py
  src/entity_extraction/hf_entity_extraction.py
  src/logs.py
  src/pipeline/entity_extraction_pipeline.py
  src/preprocessing/labelling_preprocessing.py
  tests/entity_extraction/test_labelling_data_split.py
  tests/pipeline/test_entity_extraction_pipeline.py
  tests/pipeline/test_entity_extraction_pipeline/test_gdd_text
Labels: NER

#44 Merge Dev to Main: Updated Release for xDD Team Docker Review
  .dockerignore
  docker-compose.yml
  docker/entity-extraction-pipeline/Dockerfile
  docker/entity-extraction-pipeline/README.md
  docker/entity-extraction-pipeline/requirements.txt
  requirements.txt
  src/entity_extraction/baseline_entity_extraction.py
  src/entity_extraction/hf_entity_extraction.py
  src/logs.py
  src/pipeline/entity_extraction_pipeline.py
  src/preprocessing/labelling_preprocessing.py
  tests/entity_extraction/test_labelling_data_split.py
  tests/pipeline/test_entity_extraction_pipeline.py
  tests/pipeline/test_entity_extraction_pipeline/test_gdd_text
Labels: documentation, NER

#43 Added About Page and Readme
  docker-compose.yml
  docker/data-review-tool/Dockerfile
  docker/data-review-tool/README.md
  docker/data-review-tool/requirements.txt
  src/data_review_tool/README.md
  src/data_review_tool/app.py
  src/data_review_tool/assets/about.md
  src/data_review_tool/assets/about_assets/accordions.png
  src/data_review_tool/assets/about_assets/data_review_tool_demo.mp4
  src/data_review_tool/assets/about_assets/deleted_toggle.png
  src/data_review_tool/assets/about_assets/entity_review.png
  src/data_review_tool/assets/about_assets/home.png
  src/data_review_tool/assets/about_assets/new_entity.png
  src/data_review_tool/assets/about_assets/restore.png
  src/data_review_tool/assets/finding-fossils.ico
  src/data_review_tool/assets/styles.css
  src/data_review_tool/pages/about.py
  src/data_review_tool/pages/article_review.py
  src/data_review_tool/pages/config.py
  src/data_review_tool/pages/home.py
  src/data_review_tool/pages/navbar.py
  src/logs.py
Labels: data-review-tool

#47 Data Review Tool About Page and README
  docker/data-review-tool/requirements.txt
  src/data_review_tool/README.md
  src/data_review_tool/assets/about.md
  src/data_review_tool/assets/about_assets/data_review_tool_demo.mp4
  src/data_review_tool/assets/data-review-tool-walkthrough.mp4
  src/data_review_tool/pages/about.py
Labels: data-review-tool

#64 Data review tool testing and Logging
  docker/data-review-tool/Dockerfile
  requirements.txt
  src/data_review_tool/app.py
  src/data_review_tool/pages/about.py
  src/data_review_tool/pages/article_review.py
  src/data_review_tool/pages/config.py
  src/data_review_tool/pages/home.py
  src/data_review_tool/pages/navbar.py
  src/data_review_tool/pages/not_found_404.py
  src/logs.py
  tests/data_review_tool/test_article_review.py
  tests/data_review_tool/test_home.py
Labels: data-review-tool

#65 HuggingFace Model Training
  requirements.txt
  sample_pipeline_output.json
  src/entity_extraction/hf_entity_extraction.py
  src/entity_extraction/ner_eval.py
  src/entity_extraction/training/hf_token_classification/hf_evaluate.py
  src/entity_extraction/training/hf_token_classification/huggingface_preprocess.py
  src/entity_extraction/training/hf_token_classification/run_roberta_base_training.sh
  src/entity_extraction/training/hf_token_classification/run_training.sh
  src/preprocessing/labelling_data_split.py
  tests/entity_extraction/test_hf_entity_extraction.py
  tests/entity_extraction/test_hf_evaluate.py
  tests/entity_extraction/test_huggingface_preprocessing.py
  tests/entity_extraction/test_ner_eval.py
Labels: NER

#83 Main Readme Update for Final Submission
  README.md
  assets/article_prediction_flow.png
  assets/ffossils-logo-text.png
Labels: docs

#88 Entity Extraction SRC Folder Reorg
  README.md
  assets/labelstudio-instructions/account_creation.png
  assets/labelstudio-instructions/correct_labels.png
  assets/labelstudio-instructions/global_index.png
  assets/labelstudio-instructions/green_tab.png
  assets/labelstudio-instructions/labeling.png
  assets/labelstudio-instructions/labeling_instructions.png
  assets/labelstudio-instructions/labeling_instructions_button.png
  assets/labelstudio-instructions/labelstudio_tab.png
  assets/labelstudio-instructions/org_nav.png
  assets/labelstudio-instructions/settings.png
  notebooks/2.0-entity-extraction-baselines.ipynb
  notebooks/2.1-entity-extraction-spacy.ipynb
  src/entity_extraction/LabelStudio_README.md
  src/entity_extraction/evaluation/baseline_evaluation.sh
  src/entity_extraction/evaluation/entity_extraction_evaluation.py
  src/entity_extraction/evaluation/hf_evaluate.py
  src/entity_extraction/evaluation/ner_eval.py
  src/entity_extraction/evaluation/run_huggingface_evaluation.sh
  src/entity_extraction/evaluation/run_spacy_evaluation.sh
  src/entity_extraction/evaluation/spacy_evaluate.py
  src/entity_extraction/prediction/__init__.py
  src/entity_extraction/prediction/baseline_entity_extraction.py
  src/entity_extraction/prediction/hf_entity_extraction.py
  src/entity_extraction/prediction/spacy_entity_extraction.py
  src/entity_extraction/preprocessing/README.md
  src/entity_extraction/preprocessing/huggingface_preprocess.py
  src/entity_extraction/preprocessing/labelling_data_split.py
  src/entity_extraction/preprocessing/labelling_preprocessing.py
  src/entity_extraction/preprocessing/spacy_preprocess.py
  src/entity_extraction/training/hf_token_classification/1.0-hf-ner-fine-tuning.ipynb
  src/entity_extraction/training/hf_token_classification/run_training.sh
  src/entity_extraction/training/huggingface/README.md
  src/entity_extraction/training/huggingface/__init__.py
  src/entity_extraction/training/huggingface/colab_start_training.ipynb
  src/entity_extraction/training/huggingface/ner_training.py
  src/entity_extraction/training/huggingface/run_roberta_base_training.sh
  src/entity_extraction/training/spacy/README.md
  src/entity_extraction/training/spacy/colab_start_training.ipynb
  src/entity_extraction/training/spacy/run_spacy_training.sh
  src/entity_extraction/training/spacy/spacy_transformer_train.cfg
  src/entity_extraction/training/spacy_ner/create_config.py
  src/entity_extraction/training/spacy_ner/run_spacy_training.sh
  src/pipeline/entity_extraction_pipeline.py
  src/preprocessing/spacy_preprocess.py
  tests/entity_extraction/test_baseline_entity_extraction.py
  tests/entity_extraction/test_entity_extraction_evaluation.py
  tests/entity_extraction/test_hf_entity_extraction.py
  tests/entity_extraction/test_hf_evaluate.py
  tests/entity_extraction/test_huggingface_preprocessing.py
  tests/entity_extraction/test_labelling_data_split.py
  tests/entity_extraction/test_labelling_preprocessing.py
  tests/entity_extraction/test_ner_eval.py
  tests/entity_extraction/test_spacy_entity_extraction.py
  tests/entity_extraction/test_spacy_evaluate.py
  tests/pipeline/test_entity_extraction_pipeline.py
Labels: NER

#95 Final Reportort for MDS and Simon Clean Up
  reports/final_mds/assets/references.bib
  reports/final_mds/finding-fossils-final-mds.pdf
  reports/final_mds/finding-fossils-final-mds.qmd
  reports/final_partner/assets/references.bib
  reports/final_partner/finding-fossils-final.pdf
  reports/final_partner/finding-fossils-final.qmd
Labels: docs

#98 Docker compose for article relevance
  docker-compose.yml
  docker/article-relevance/Dockerfile
  src/article_relevance/relevance_prediction_parquet.py
Labels: article-relevance
